project:
  type: website
  output-dir: _site
  resources:
    - CNAME
    - logo_square.png

website:
  title: "Flaky - Pie Shop in Zurich"
  site-url: "https://www.flakypieshop.com"
  search: false
  navbar:
    left:
      - href: index.qmd#home
        text: Home
      - href: index.qmd#products
        text: Products
        menu:
          - text: "Cinnamon Apple Crumble Pie"
            href: cinnamon-apple-crumble-pie-zurich.qmd
          - text: "Blueberry Maple Chess Pie"
            href: blueberry-maple-chess-pie-zurich.qmd
          - text: "Chocolat-y Pecan Pie"
            href: pecan-pie-zurich.qmd
          - text: "Pumpkin Pie"
            href: pumpkin-pie-zurich.qmd
      - href: index.qmd#about
        text: About
      - href: order-pies-zurich.qmd
        text: Order
metadata:
  lang: en
  description: "Home-based microbakery in ZÃ¼rich selling homemade American pies & treats. Pickup & delivery."

format:
  html: 
    include-after-body: 
    - footer.html
    
    favicon: logo_square.png
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header: head.html

editor: visual
